### ISSUE TITLE
TestCase Failed

### ISSUE THREAD

**Issue by daryer** [ftomassetti/JavaCC2ANTLR#1]
hello,there some error in the convert, can you help?

-junit4 com.strumenta.javacc.JavaGrammarTest
Parsing src\test\resources\guava-src\com\google\common\annotations\Beta.java
Parsing src\test\resources\guava-src\com\google\common\annotations\GwtCompatible.java
Parsing src\test\resources\guava-src\com\google\common\annotations\GwtIncompatible.java
Parsing src\test\resources\guava-src\com\google\common\annotations\package-info.java
Parsing src\test\resources\guava-src\com\google\common\annotations\VisibleForTesting.java
Parsing src\test\resources\guava-src\com\google\common\base\Absent.java
Parsing src\test\resources\guava-src\com\google\common\base\AbstractIterator.java
Parsing src\test\resources\guava-src\com\google\common\base\Ascii.java

**org.snt.inmemantlr.exceptions.ParsingException**: (line 630,char 34): mismatched input '')' expecting {'instanceof', ')', '[', '.', '=', '<', '?', '==', '<=', '>=', '!=', '||', '&&', '++', '--', '+', '-', '*', '/', '&', '|', '^', '%', '<<', '+=', '-=', '*=', '/=', '&=', '|=', '^=', '%=', '<<=', '>>=', '>>>=', '->', '::', '>'}

	at org.snt.inmemantlr.GenericParser.parse(GenericParser.java:544)
	at org.snt.inmemantlr.GenericParser.parse(GenericParser.java:391)
	at org.snt.inmemantlr.GenericParser.parse(GenericParser.java:354)
	at com.strumenta.javacc.JavaGrammarTest.parseJavaFile(JavaConversion.kt:130)
	at com.strumenta.javacc.JavaGrammarTest.parseDir(JavaConversion.kt:123)
	at com.strumenta.javacc.JavaGrammarTest.parseDir(JavaConversion.kt:121)
	at com.strumenta.javacc.JavaGrammarTest.parseDir(JavaConversion.kt:121)
	at com.strumenta.javacc.JavaGrammarTest.parseDir(JavaConversion.kt:121)
	at com.strumenta.javacc.JavaGrammarTest.parseDir(JavaConversion.kt:121)
	at com.strumenta.javacc.JavaGrammarTest.canParseAllGuava(JavaConversion.kt:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code -1

**Comment by ftomassetti** [comment]
hi @daryer , I would need the source code of the grammar you are using to verify this

**Comment by daryer** [comment]
in the source code with path : src\test\resources\guava-src\com\google\common\base\Ascii.java

**Comment by daryer** [comment]
> hi @daryer , I would need the source code of the grammar you are using to verify this

in the source code with path : src\test\resources\guava-src\com\google\common\base\Ascii.java

the grammar file is also in the project：JavaCC2ANTLR/tree/master/src/main/antlr/Java_*.g4

**Comment by ftomassetti** [comment]
Thank you for reporting this. I will setup Travis CI and then look into this

**Comment by daryer** [comment]
> Thank you for reporting this. I will setup Travis CI and then look into this

Excuse me, is there any progress?

**Comment by ftomassetti** [comment]
Hi @daryer at the moment I am afraid I do not have much time to look into it (too busy with clients!). Any help to fix this would be appreciated

**Comment by daryer** [comment]
i am not sure if it can be solved, i will try to fix it
